anfisa_for_friends/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.description, name='description'),
]

anfisa_for_friends/anfisa_for_friends/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('about/', include('about.urls', namespace='about')),
    path('ice_cream/', include('ice_cream.urls', namespace='ice_cream')),
    path('admin/', admin.site.urls),
]

anfisa_for_friends/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

anfisa_for_friends/ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('', views.ice_cream_list, name='ice_cream_list'),
    path('<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

anfisa_for_friends/about/models.py
from django.db import models

# Create your models here.

anfisa_for_friends/homepage/models.py
from django.db import models

# Create your models here.

anfisa_for_friends/ice_cream/models.py
from django.db import models

# Create your models here.

anfisa_for_friends/about/views.py
from django.shortcuts import render


def description(request):
    template = 'about/description.html'
    return render(request, template)

anfisa_for_friends/homepage/views.py
from django.shortcuts import render


def index(request):
    template = 'homepage/index.html'
    return render(request, template)

anfisa_for_friends/ice_cream/views.py
from django.shortcuts import render

ice_cream_catalog = [
    {
        'id': 0,
        'title': 'Классический пломбир',
        'description': 'Настоящее мороженое, для истинных ценителей вкуса. '
                       'Если на столе появляется пломбир — это не надолго.',
    },
    {
        'id': 1,
        'title': 'Мороженое с кузнечиками',
        'description': 'В колумбийском стиле: мороженое '
                       'с добавлением настоящих карамелизованных кузнечиков.',
    },
    {
        'id': 2,
        'title': 'Мороженое со вкусом сыра чеддер',
        'description': 'Вкус настоящего сыра в вафельном стаканчике.',
    },
]


def ice_cream_detail(request, pk):
    template = 'ice_cream/detail.html'
    context = {'ice_cream': ice_cream_catalog[pk]}
    return render(request, template, context)


def ice_cream_list(request):
    template = 'ice_cream/list.html'
    context = {'ice_cream_list': ice_cream_catalog}
    return render(request, template, context)

anfisa_for_friends/templates/about/description.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Описание проекта
{% endblock %}
{% block content %}
  <h1>Описание проекта</h1>
{% endblock %}

anfisa_for_friends/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      {% block content %}
      {% endblock %}
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

anfisa_for_friends/templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Главная
{% endblock %}
{% block content %}
  <h1>Главная страница</h1>
{% endblock %}

anfisa_for_friends/templates/ice_cream/detail.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Подробное описание мороженого
{% endblock %}
{% block content %}
  <h1>Подробное описание мороженого</h1>
  <h3>{{ ice_cream.title }}</h3>
  <p>{{ ice_cream.description }}</p>
{% endblock %}
 

anfisa_for_friends/templates/ice_cream/list.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Каталог мороженого
{% endblock %}
{% block content %}
  <h1>Каталог мороженого</h1>
  <ul>
    {% for ice_cream in ice_cream_list %}
      <li>
        <h3>{{ ice_cream.title }}</h3>
        <p>{{ ice_cream.description|truncatewords:10 }}</p>
        <a href="{% url 'ice_cream:ice_cream_detail' ice_cream.id %}">подробнее</a>
      </li>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </ul>
{% endblock %}

anfisa_for_friends/templates/includes/footer.html
<footer>
  <p>Копирайт, год создания</p>
</footer> 

anfisa_for_friends/templates/includes/header.html
{% load static %}
<header>
  <img src="{% static 'img/logo.png' %}" height="50" alt="">
  <nav>
    <ul>
      <li>
        <a href="{% url 'homepage:index' %}">Главная</a>  
      </li>
      <li>
        <a href="{% url 'ice_cream:ice_cream_list' %}">Каталог мороженого</a>       
      </li>
      <li>
        <a href="{% url 'about:description' %}">О проекте</a>
      </li>
    </ul>
  </nav>
</header>